### ISSUE TITLE
findDocuments throwing an error

### ISSUE THREAD

**Issue by tomjmul** [pmorjan/couchdb-promises#2]
FindDocuments is not setting `postContentType` resulting in an error getting thrown:

"value" required in setHeader" content-type

**Comment by pmorjan** [comment]
This happens if the function argument is of the wrong type.
In ```findDocuments(baseUrl, dbName, queryObj)``` 
```queryObj``` must be of the type 'object' as shown in the example. 'string'  (or JSON) is wrong.
Can you give an example?

**Comment by pmorjan** [comment]
no response, closing
