### ISSUE TITLE
Support for HTTP COPY

### ISSUE THREAD

**Issue by dsquier** [pmorjan/couchdb-promises#3]
I realize it's non-standard, but it appears CouchDB supports the HTTP COPY protocol:

https://wiki.apache.org/couchdb/HTTP_Document_API#COPY

Any chance of adding this to the library? I can submit a PR if you're open to it.

Thanks!

**Comment by pmorjan** [comment]
yes PR are welcome. Pls have a look at the develop branch that uses a slightly different approach.
Thanks.

**Comment by dsquier** [comment]
Here is the PR: https://github.com/pmorjan/couchdb-promises/pull/4

Happy to answer questions or make changes, just let me know!

**Comment by pmorjan** [comment]
Thanks!  I just pushed v2.0.0 to npmjs.com

**Comment by dsquier** [comment]
My pleasure!
