### ISSUE TITLE
support for update handlers

### ISSUE THREAD

**Issue by bigfish** [pmorjan/couchdb-promises#5]
I tried to call an update handle defined in design view, but couldn't find a method to achieve that -- kept getting 409 conflict. 
https://wiki.apache.org/couchdb/Document_Update_Handlers
I can achieve this with nano's atomic() :
https://github.com/dscape/nano#dbatomicdesignname-updatename-docname-body-callback
Otherwise couchdb-promises is great, thanks!

**Comment by pmorjan** [comment]
I've never used Document Update Handles. It seems this requires two new methods. 
http://docs.couchdb.org/en/latest/api/ddoc/render.html#db-design-design-doc-update-update-name
and
http://docs.couchdb.org/en/latest/api/ddoc/render.html#db-design-design-doc-update-update-name-doc-id
I'll have a look when I get the time. It would be good to have the most simple example.

**Comment by pmorjan** [comment]
I added new update functions to master (22d768b7eb3aa59ce13b125ef17223274163910b)
There is also a short example [update_handler.js](https://github.com/pmorjan/couchdb-promises/blob/master/examples/update-handler.js)
Please let me know if this works for you.
Note that the API did change and there is more to come.

**Comment by dsquier** [comment]
Thanks for this-- I have a few use cases and will also give it a try.

**Comment by pmorjan** [comment]
I don't like the naming. It should be close to the CouchDB API but not that long. Also there might be additional functions to be implemented. PR welcome.

**Comment by pmorjan** [comment]
just released in v3.0.0

**Comment by bigfish** [comment]
thanks, I'll check it out!

**Comment by bigfish** [comment]
I can confirm it works.
