### ISSUE TITLE
Ensure optional requestTimeout is integer

### ISSUE THREAD

**Issue by dsquier** [pmorjan/couchdb-promises#6]
I ran into a case where passing `requestTimeout` from an external source resulted in the value getting converted from an integer to a string which prevented the module from loading.

The specific case happened when AWS CloudFormation read `requestTimeout` from a configuration file stored in S3. Even though the value was stored as an integer, it got converted to a string before getting passed to our application.

A work-around was to run a `parseInt()` on the value inside the code, but I was thinking this might be something the library can do, i.e., something like:

```
module.exports = function (opt) {
  const config = {
    requestTimeout: 10000, // ms
    verifyCertificate: true
  }

  // added check to ensure an optional requestTimeout is always an integer
  if (opt.requestTimeout && typeof opt.requestTimeout !== 'integer') {
    opt.requestTimeout = parseInt(opt.requestTimeout);
  }

  Object.assign(config, opt)

  if (typeof config.baseUrl !== 'string') {
    throw new Error(`invalid or missing property 'baseUrl'`)
  }
```

Alternatively, this could be done after `Object.assign` by changing `const config` -> `let config`.

Happy to submit a PR with either approach if your okay with it.

**Comment by pmorjan** [comment]
yes, checking the timeout argument makes totally sense.
But I think fixing an invalid timeout argument by running parseInt inside the library might cover a mistake by the user that's hard to find later on.
What about a simple check right after the Object.assign:
```
if (typeof config.requestTimeout !== 'number' || isNaN(config.requestTimeout)) {
    throw ...
}
```
Having a new test case for invalid arguments would be nice too. WDYT?

**Comment by dsquier** [comment]
That works for me. Getting an error for this case will make diagnosing this case super-quick.

I can submit a PR if you like, just let me know.

**Comment by pmorjan** [comment]
yes please

**Comment by pmorjan** [comment]
fixed by 17d2c5e7b027c65248710a1ed56f5624c17a77a0

**Comment by dsquier** [comment]
Sorry, been out of town the past week. Looks like you got this taken care of, thanks much!

**Comment by dsquier** [comment]
Thanks again, going to close since this is done.
