### ISSUE TITLE
createDatabase() against pouchdb times out when reusing the couch client instance

### ISSUE THREAD

**Issue by hrbu** [pmorjan/couchdb-promises#8]
Created a client this way:
```javascript
const couchClient = require('couchdb-promises');
let couch = couchClient({
      baseUrl: `http://localhost:5990`,
      requestTimeout: 1000
    });
```
Using the same `couch` instance to create a document AND a database afterwards leads to a timeout when callin `couch.createDatabase('bar');` >>> `"data":{"error":"request timed out"},"status":500`

```javascript
  couch.createDocument('actions', { city: 'berlin' })
      .then(() => {
        console.log(`Creating another database ...`);
        return couch.createDatabase('bar');
      })
      .then((value) => {
        console.log('Database created.');
        done();
      })
      .catch((reason) => {
        done(new Error(JSON.stringify(reason)));
      });
```

See the mocha based test attached ([create-database.spec.zip](https://github.com/pmorjan/couchdb-promises/files/840720/create-database.spec.zip)). The test uses a pouchdb-server with in-memory backend:
```javascript
package.json:
  "devDependencies": {
    "couchdb-promises": "^3.0.0",
    "spawn-pouchdb-server": "^3.3.3",
    "memdown": "^1.2.4",
```

**Comment by pmorjan** [comment]
I can't reproduce your problem. On CouchDB your code works as expected. 
I never tried pouchdb.

**Comment by hrbu** [comment]
Right. Doing the same using CouchDB (2.0.0) works as expected. 
So I close this issue. Thanx for your time.
